server:
  port: 10001
  shutdown: graceful

spring:
  application:
    name: order-service

eureka:
  instance:
    instance-id: order-microservice-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9900/eureka